global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'scan_pt'
    metrics_path: /
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - www.ptsecurity.com
